repos:
  - repo: https://github.com/psf/black
    rev: '21.5b2' # https://github.com/psf/black/tags
    hooks:
      - id: black
        language_version: python3
        args: [--check]

  - repo: https://gitlab.com/pycqa/flake8
    rev: '3.9.2' # https://gitlab.com/pycqa/flake8/-/tags
    hooks:
      - id: flake8

  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: 'v0.812' # https://github.com/python/mypy/tags
    hooks:
      - id: mypy
